name: Maven build test

on:
  pull_request:
    branches: [ "github_actions_test" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Run 1.16.5 BuildTools
      uses: SpraxDev/Action-SpigotMC@v4
      with:
        versions: 1.16.5
    - name: Run 1.17.1 BuildTools
      uses: SpraxDev/Action-SpigotMC@v4
      with:
        versions: 1.17.1
        remapped: true
    - name: Run 1.18.2 BuildTools
      uses: SpraxDev/Action-SpigotMC@v4
      with:
        versions: 1.18.2
        remapped: true
    - name: Run 1.19.2 BuildTools
      uses: SpraxDev/Action-SpigotMC@v4
      with:
        versions: 1.19.2
        remapped: true
    - name: Build with Maven
      run: mvn -B package
